### ISSUE TITLE
vim_removed_plugins undefined variable

### ISSUE THREAD

**Issue by danoost** [ctorgalson/ansible-role-vim#12]
Great role - very easy to use. However, I can't get the vim_removed_plugins var to work properly. The error message is as follows:

```
fatal: [<snip>]: FAILED! => {"msg": 
  "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'directory'

  The error appears to be in '/home/danielo/.ansible/roles/ctorgalson.vim/tasks/remove-plugin.yml': line 6, column 3, but may
  be elsewhere in the file depending on the exact syntax problem.

  The offending line appears to be:
  - name: Determine '{{ vim_plugin.directory }}' plugin install directory.
    ^ here
  We could be wrong, but this one looks like it might be an issue with
  missing quotes. Always quote template expression brackets when they
  start a value. For instance:

      with_items:\n      - {{ foo }}

  Should be written as:

      with_items:
        - \"{{ foo }}\"
"}
```

My declaration is the same as a working declaration for vim_installed_plugins:

```
    vim_installed_plugins:
      - repo: "https://github.com/vim-airline/vim-airline.git"
        type: "start"
    vim_removed_plugins:
      - repo: "https://github.com/vim-airline/vim-airline.git"
        type: "start"
```
